version: '3.1'

services:
  web:
    restart: always
    image: pec/web
    container_name: pec_web
    ports:
      - "8001:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "5"
